### ISSUE TITLE
Related project: entr

### ISSUE THREAD

**Issue by pylipp** [maaslalani/crow#4]
Not a feature request but merely a note about another similar project, [entr](https://github.com/eradman/entr/). Do you know it? How do you think entr and crow compare to each other? Maybe it's worth mentioning it in the readme as related project.

**Comment by maaslalani** [comment]
To be entirely honest I think `entr` is better in terms of software.

I watched a video on entr a few months ago and really thought it was cool, a few months later when I had a use for it (rerunning go tests on save) I forgot what it was called 😅. After a bit of searching, I decided to build it a similar tool from scratch to solve the same problem. So I would say theres no real benefit to using crow over `entr`. I guess because `crow` is written in Go it appeals to gophers since if they want to add features they can easily contribute and since `crow` is newer I'm more likely to add their changes in.

But yeah, entr is great!

I will add a list of alternatives to the README like `reflex` and `entr` so that people can choose for themselves which they want to use.
